### ISSUE TITLE
Add tests for new 2.1 features to TCK

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/authorization#113]
The TCK sub-tree for Jakarta Authorization tests is located here:

https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/jacc

New features:

https://github.com/jakartaee/authorization/issues?q=is%3Aissue+is%3Aclosed+milestone%3A2.1

Features used in practice by an impl:

https://github.com/eclipse-ee4j/exousia/blob/2.1.0-M1/impl/src/main/java/org/glassfish/exousia/modules/def/DefaultPolicy.java#L55

**Comment by starksm64** [comment]
A first pass is in https://github.com/eclipse-ee4j/jakartaee-tck/pull/939

**Comment by arjantijms** [comment]
This is essentially done. Strengthening the tests, if needed, can be the topic of a new issue.
