### ISSUE TITLE
TCK Challenge: com.sun.ts.tests.jacc.provider.TSPolicy performs getPolicyConfiguration() without subsequent pc.commit()

### ISSUE THREAD

**Issue by brideck** [jakartaee/authorization#118]
**Challenged Tests:**
The tests implicitly added in https://github.com/eclipse-ee4j/jakartaee-tck/pull/939, which because they were added into Authorization provider code, result in the following 14 failures:
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#ADM_InRole_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#EjbIsAuthz_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#EjbNotAuthz_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#EjbSecRoleRef_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#excludeTest_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#InterMediateBean_CallerPrincipal_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#MGR_InRole_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#TargetBean_CallerPrincipal_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/ejb/mr/Client.java#uncheckedTest_from_ejblitesecuredjsp
[javatest.batch] FAILED........com/sun/ts/tests/jacc/web/containerContracts/Client.java#IsUserInRole
[javatest.batch] FAILED........com/sun/ts/tests/jacc/web/containerContracts/Client.java#WebUserDataPermission
[javatest.batch] FAILED........com/sun/ts/tests/jacc/web/principal2role/Client.java#PrincipalToRoleMapping
[javatest.batch] FAILED........com/sun/ts/tests/jacc/web/providerContracts/Client.java#PermissionsToRole
[javatest.batch] FAILED........com/sun/ts/tests/jacc/web/providerContracts/Client.java#WildCardAuthConstraint

Test Source: [com.sun.ts.tests.jacc.provider.TSPolicy](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jacc/provider/TSPolicy.java#L192)

**TCK Version:**
Jakarta Platform 10.0.0

**Tested Implementation:**
Open Liberty

**Description:**
The new testing added in EE 10 to cover the API's new getPolicyConfiguration() methods has some unintended side effects.

Per [section 3.1.1.1 of the Authorization 2.1 specification](https://jakarta.ee/specifications/authorization/2.1/jakarta-authorization-spec-2.1.html#a257), "A policy context in the inService state must be transitioned to the open state when it is returned as a result of a call to getPolicyConfiguration."

However, per [section 4.9 of the Authorization 2.1 specification](https://jakarta.ee/specifications/authorization/2.1/jakarta-authorization-spec-2.1.html#a745) "a Policy provider must return that a tested permission has not been granted if ... the inService method of the PolicyConfigurationFactory associated with the provider would return false."  In other words, the policy has to be in the inService state in order to actually test a permission.

Unfortunately, the new testing added these getPolicyConfiguration() calls (setting the state to open) immediately prior to running the pre-existing logic to test the permissions.  This can't possibly work because the policy will never be in the necessary inService state, and all checks will be rejected.  Section 3.1.1.1 states that "a policy context is transitioned to the inService state by calling the commit method, and only a policy context in the open state may be transitioned to the inService state," so this could be easily fixed by adding a call to commit the PolicyConfiguration prior to continuing with the permissions testing.

**Comment by brideck** [comment]
I did a cursory examination of Exousia's default policy implementation (https://github.com/eclipse-ee4j/exousia/tree/2.1.0/impl/src/main/java/org/glassfish/exousia/modules/def) and it does not appear to do the state checking that section 4.9 asks for, which would explain how anyone using it would be able to pass the new TCK without issue.

**Comment by brideck** [comment]
As one would expect, based on section 4.9, Open Liberty currently rejects all of these permission checks, resulting in the tests failing with a 403 response:

```
[javatest.batch] FINE: sun.net.www.MessageHeader@276438c98 pairs: {GET /jacc_ejb_mr_ejblitesecuredjsp_vehicle_web/ejblitesecuredjsp_vehicle.jsp?testName=ADM_InRole HTTP/1.1: null}{Authorization: Basic ajJlZTpqMmVl}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/11.0.12}{Host: localhost:9080}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
[javatest.batch] Failed to connect to the test webapp.java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:9080/jacc_ejb_mr_ejblitesecuredjsp_vehicle_web/ejblitesecuredjsp_vehicle.jsp?testName=ADM_InRole

**Comment by arjantijms** [comment]
@brideck 

> and it does not appear to do the state checking that section 4.9 asks for

Do you mean the checks in the link below, or something else?

https://github.com/eclipse-ee4j/exousia/blob/2.1.0/impl/src/main/java/org/glassfish/exousia/modules/def/DefaultPolicyConfigurationStateMachine.java

> which would explain how anyone using it would be able to pass the updated TCK without issue.

The certification of Exousia is done with the Locked Policy, which can be found here: https://github.com/eclipse-ee4j/exousia/tree/2.1.0/impl/src/main/java/org/glassfish/exousia/modules/locked

**Comment by arjantijms** [comment]
@brideck 
> Unfortunately, the new testing added these getPolicyConfiguration() calls (setting the state to open)

From the spec at https://github.com/jakartaee/authorization/blob/master/api/src/main/java/jakarta/security/jacc/PolicyConfigurationFactory.java#L225

_If at the time of the call, the identified policy context does not exist in the provider, then the policy context
will <strong>not</strong> be created in the provider and a null will be returned. **No state transition of any kind
is allowed to occur, the <code>PolicyConfiguration</code> instance is to be returned as-is.**_

(emphasis mine)

**Comment by emilytee** [comment]
The 2 new methods will no longer set the state to OPEN.    I didnt expect the underlying behavior to change for the 2 additional methods from what the original was doing.

**Comment by arjantijms** [comment]
> I didnt expect the underlying behavior to change for the 2 additional methods from what the original was doing.

The entire point of adding those two methods was so that a Policy (and soon, its replacement) can get hold of the configuration in a portable way without any side-effects.
