### ISSUE TITLE
Why not simply drop Jakarta Authorization in favor of new features in other specs?

### ISSUE THREAD

**Issue by starksm64** [jakartaee/authorization#120]
We have very little usage of Authorization in Wildfly and EAP. With the need to completely revamp this spec do to JEP 411 changes, why not simply deprecate and remove JACC from the platform? Other cloud friendly authorization schemes can be developed as part of Jakarta Security.

**Comment by arjantijms** [comment]
There's no complete revamp needed. Just a replacement for Policy, which can be more or less a copy of the Java SE Policy class with some small refinements.

I think the little usage in WildFly and EAP comes from the fact you don't have it enabled by default.

Having a repository of permissions (a permission store, essentially) is by itself quite powerful. It's mostly the fact that the SPI have been a) made hard to access (artefacts only really installable on the server level) and b) WF and EAP not enabling it by default, that, IMHO, got us into this situation.

Both are relatively easy to rectify.

I do wonder what you have in mind as "cloud friendly' alternative. Jakarta Authorization primarily stores the security constraints from web.xml (and related annotations) now, transformed into Permission instances in a standard format.

**Comment by pdudits** [comment]
> Just a replacement for Policy, which can be more or less a copy of the Java SE Policy class with some small refinements.

I'm afraid a replacement for `PolicyContext` is also necessary, as containers have no means of "preventing the methods of the PolicyContext class from being called from calling contexts that are not authorized to call these methods." without Security Manager.

At first sight it looks that it will need to split to multiple interfaces and a some service loader mechanisms to handle them. I'll file a separate issue.
