### ISSUE TITLE
Compatibility certification request for Exousia 3.0.0-M3

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/authorization#164]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [Exousia 3.0.0-M3](https://github.com/eclipse-ee4j/exousia/releases/tag/3.0.0-M3-RELEASE)
  [Eclipse Glassfish 8.0.0-M5](https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/8.0.0-M5/glassfish-8.0.0-M5.zip) (JDK 21)
   [Eclipse Glassfish 8.0.0-JDK-17-M5](https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/8.0.0-JDK17-M5/) (JDK 17)
- [x] Specification Name, Version and download URL
  [Jakarta Authorization, 3.0](https://jakarta.ee/specifications/authorization/3.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Authorization TCK 3.0](https://download.eclipse.org/security/jakartaee11/staged/eftl/jakarta-authorization-tck-3.0.0.zip), SHA-256: `70f2e15334cfc525fa3b2ab575a96bd06cde942302d45d12da040242ff969fe8`
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://github.com/eclipse-ee4j/exousia/wiki/Jakarta-Authorization-3.0-TCK-Exousia-Results)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment (build 21.0.2+13-58) OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)
  openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Debian GNU/Linux 10 (buster)
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by Emily-Jiang** [comment]
[Jakarta Authorization, 2.1](https://jakarta.ee/specifications/authorization/3.0/) should be [Jakarta Authorization, 3.0](https://jakarta.ee/specifications/authorization/3.0/)

**Comment by Emily-Jiang** [comment]
[This](https://github.com/eclipse-ee4j/exousia/wiki/Jakarta-Authorization-3.0-TCK-Exousia-Results) page also needs to update the version number of Jakarta Authentication

**Comment by arjantijms** [comment]
> [This](https://github.com/eclipse-ee4j/exousia/wiki/Jakarta-Authorization-3.0-TCK-Exousia-Results) page also needs to update the version number of Jakarta Authentication

It is done

**Comment by arjantijms** [comment]
As the project lead, I assert this is completed and accepted.
