### ISSUE TITLE
Promote authorization 3.0

### ISSUE THREAD

**Issue by Emily-Jiang** [jakartaee/authorization#166]
Project Team:

- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [ ] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from Draft to Final.
- [x] approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.
- [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
@Emily-Jiang Can you run the release script for the TCK?

From:
https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/authorization/jakarta.authorization-api/3.0.0/

To:
https://download.eclipse.org/jakartaee/authorization/3.0/jakarta-authorization-tck-3.0.0.zip

**Comment by arjantijms** [comment]
All done :)
