### ISSUE TITLE
Build failure with missing dependency

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/authorization#88]
Hi,

was reviewing for Jakarta EE 9 and wanted to build it all from scratch but looks like it's failing for me.

Steps

rm -rf ~/.m2/repository
git clone git@github.com:eclipse-ee4j/authorization.git
mvn clean install

This gives me 

[ERROR] Failed to execute goal on project jakarta.authorization-api: Could not resolve dependencies for project jakarta.authorization:jakarta.authorization-api:jar:2.0-SNAPSHOT: Could not find artifact jakarta.servlet:jakarta.servlet-api:jar:5.0.0 in central (https://repo.maven.apache.org/maven2)

**Comment by pzygielo** [comment]
Activate `staging` profile.

**Comment by jeanouii** [comment]
Shouldn't the project build by default?

**Comment by pzygielo** [comment]
> Shouldn't the project build by default?

Forgive me. I didn't know you are committer here (so you probably know better).
I read your issue as "I can't build it", but apparently you meant something else.

**Comment by jeanouii** [comment]
No worries.
I was asking a question, so any feedback or help is always welcome. And sorry if it was not clear

Yes my goal was to try to track any old dependency we may have miss because the dependency is already available in the local Maven repo.

But as an open discussion I believe we should be able to build a project without having to activate a profile. At least not manually (-Pprofile-name)

**Comment by arjantijms** [comment]
> Shouldn't the project build by default?

We could consider activating the `staging` profile by default as long as there are staging dependencies. Though non of the other projects have this for now. Maybe something we can do for the entire platform when Jakarta EE 10 is in staging.

**Comment by arjantijms** [comment]
> But as an open discussion I believe we should be able to build a project without having to activate a profile. At least not manually (-Pprofile-name)

Normally, of course. Though this is a special case if you want when everything is in staging and there are mutual and phased dependencies.
